title: MendelGameteCompetition.jl
description: This analysis option implements a gamete competition analysis, which is a generalization of the TDT analysis.
google_analytics: 
show_downloads: true
theme: jekyll-theme-slate

gems:
  - jekyll-mentions
